### ISSUE TITLE
Add PCB .kicad and Plate .svg?

### ISSUE THREAD

**Issue by oliviahanley** [Slavfot/gallium-keyboard#1]
Hey! I really like this keyboard layout, and it accomplishes a lot of what I was looking to do in a Redox modification I was plotting (especially in terms of eliminating the 1.25u left and right mods for keycap compatibility). Would you be able to post the .kicad files you used to generate the PCB? I'm very interested in building my own (and maybe even designing another type of case). Would you be willing to do that? Doesn't need to be clean--I'd be appreciative either way.

**Comment by Slavfot** [comment]
Hi! 
I can upload everything.
But i have a problem with the keyboard that i have opened an issue at the redox Github. [https://github.com/mattdibi/redox-keyboard/issues/55](url)
The problem is interference making it hard to use in some environments. 
I just it daily at my work and it works really good except that i sometimes have to replug the usb receiver at startup to get a good connection.
At home it is almost unusable because of interference. Missing key presses and high latency.

**Comment by Slavfot** [comment]
I have uploaded kicad files, case .stl files and a .dxf of the plate.

**Comment by oliviahanley** [comment]
Thanks so much! I really appreciate it. And duly noted on the interference issues--I'll keep that in mind!
